hosts:
    - name: server-01
      macAddress: 00:1A:2B:3C:4D:5E
    - name: server-02
      macAddress: 00:1A:2B:3C:4D:5F
namePrefix: server- # optional prefix, default: "compute-"
filter:
    macPrefix:
        - 00:1A:2B:3C:4D:5E
        - 00:1A:2B:3C:4D:5F
        - 00:AA:BB
