server6:
    listen:
    - "[::]"

    plugins:
        # mandatory for RFC compliance
        - server_id: LL 00:de:ad:be:ef:00
        # always provide the same IP address, no matter who's asking:
        # - bluefield: 2001:db8::1
        # implement HTTPBoot
        - httpboot: http://[2001:db8::1]/image.uki
        # add leased IPs to ironcore's IPAM
        - ipam: ipam-ns ipam-subnet1,ipam-subnet2,some-other-subnet
        # lease IPs based on /127 subnets coming from relays running on the switches
        - onmetal:
        # announce DNS servers per DHCP
        - dns: 2001:4860:4860::6464 2001:4860:4860::64
        # implement (i)PXE boot
        - pxeboot: tftp://[2001:db8::1]/ipxe/x86_64/ipxe http://[2001:db8::1]/ipxe/boot6
        # create Endpoint objects in kubernetes
        - metal: inventory.yaml